### ISSUE TITLE
NZBHydra2 Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings.

### ISSUE THREAD

**Issue by CTParkinson** [lidarr/Lidarr#1037]
**Describe the bug**
Using NZBHydra2 as a Newznab indexer, cannot save config because "Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings."

But the I can search manually within Hydra and get results.
Why is it that Lidarr struggles with this? Both Sonarr and Radarr handle it just fine...
Is Lidarr searching for _anything_ when testing an indexer?
Can I add a test search term for it to find results with and then let me use the indexer?

But here's the kicker, also using Hydra as a Torznab indexer and Lidarr has no problem there.
I can search for torrents with Hydra without any issues.
Beyond frustrated with it.

**Comment by ta264** [comment]
Lidarr is deliberately not searching for anything - it's attempting the standard RSS update (fetching all recent releases) and not getting any results. I think your hydra config is wrong somewhere. You should be able to see the exact query run by lidarr in the hydra history and rerun to verify no results. Note that this query could he different to a manual search in hydra since hydra applies different settings. Then you need to figure out why and fix it. Please jump on the discord channel for further support.

**Comment by CTParkinson** [comment]
It's cool, I edited lidarr.db and manually enabled the indexer.
Now it works.
