### ISSUE TITLE
Torznab test/save with test categories.

### ISSUE THREAD

**Issue by reemplazable** [Lidarr/Lidarr#1062]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to add a new Torznab from Jackett and there is no audio releases having to add another category (usually films 2000) in the configuration.

**Describe the solution you'd like**
Have another field for Torznab indexers where there is a test category.

**Describe alternatives you've considered**
Allow to save the Torznab indexer without checking the data, I know Jackett will pass the test anyway.

**Additional context**

[AB#410](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/410)

**Comment by maddhin** [comment]
hi @reemplazable, I am having exactly the same issue but cannot figure out how to "add another category (usually films 2000) in the configuration" so I can actually connect a new indexer from Jacket. At the moment, I cannot add any because of the error message. In the configuration I actually cannot add categories like it is possible in Sonarr.
