### ISSUE TITLE
Able to add video only releases, which causes UI bugs

### ISSUE THREAD

**Issue by addisonbabcock** [lidarr/Lidarr#1063]
**Describe the bug**
I'm able to add video only releases to lidarr through manually searching. This causes problems with the edit dialog, which receives no release info from the API.

**To Reproduce**
1. Manually search for a video only release. For example: https://musicbrainz.org/release-group/d762b65a-6a0c-372b-bc88-f0293cbe5894
2. Add it to lidarr.
3. Open the edit dialog, 
![image](https://user-images.githubusercontent.com/2836233/72666390-feda7f80-39ce-11ea-8fff-bc7434bcbba1.png)

**Expected behavior**
Lidarr should not be able to add video only releases.

**Screenshots**
See above.

**Logs**
N/A

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1604
 - Operating System: linuxserver/lidarr:preview on Windows 10.

**Additional context**
Created after discussing in discord.

**Comment by hikaricore** [comment]
To counter this stance, I have several video releases that I've converted to audio files as they are listed in such a way on Musicbrainz that individual tracks can be isolated from them. Some examples:

https://musicbrainz.org/release/12e333bf-62f3-4c5f-8ea8-755b8bb3bb54
https://musicbrainz.org/release/ff544be3-7009-493f-bf7c-5e58b70caac7

Since converting these to audio only files locally is impossibly easy, why wouldn't they be allowed to be listed in people's libraries?

It seems like all the needed data to permit their import exists already. Wouldn't the better option be to fix the (likely simple) bug that causes this failure instead?
