### ISSUE TITLE
Feature Request Limit size of album art

### ISSUE THREAD

**Issue by nsater** [Lidarr/Lidarr#1076]
### Description of request and what problem are you looking to solve?
Lidarr is finding some super high res album art. Far too large for normal user's needs. 

Looking for an option for set the image size limit, or even a way for Lidarr to resize images with ImageMagick or the likes. 

### Other Information
Total size:
![2020-02-04 22_38_22-Unraid (Juniper)](https://user-images.githubusercontent.com/30016839/73817373-972e7d80-479f-11ea-988b-019bd39e8735.png)

Biggest offender:
![2020-02-04 22_39_03-Unraid (Juniper)](https://user-images.githubusercontent.com/30016839/73817374-9ac20480-479f-11ea-8ceb-80f8f13e47cd.png)

[AB#411](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/411)

**Comment by goldenpipes** [comment]
+1000 lol these files are way too large,

**Comment by mattboy9921** [comment]
I really would like to see this, Lidarr eats all my drive space with the album covers.

**Comment by hugalafutro** [comment]
+1 for this I just spent whole afternoon removing 50-200MB pictures from albums that swole to 1-2GB from 200-300MB.

For now I completely disabled metadata processing in Lidarr and manage metadata via Picard (in result the only difference is the dividing character between genres)

**Comment by lbesnard** [comment]
I'm in the same boat! would love a limit. Currently having 12Gb of media cover on my ssd

**Comment by 6cUbi57z** [comment]
Just looking through some of the code and it seems that images are resized into various sizes when they are downloaded but the original is kept as is: https://github.com/Lidarr/Lidarr/blob/f50556d4d5ad84812fc1ee14af2d1f4d01bf9c07/src/NzbDrone.Core/MediaCover/MediaCoverService.cs#L235-L258

When the cover is then retrieved, the height of the image can be specified and it will retrieve the relevant file: https://github.com/Lidarr/Lidarr/blob/f50556d4d5ad84812fc1ee14af2d1f4d01bf9c07/src/NzbDrone.Core/MediaCover/MediaCoverService.cs#L70-L82

Unfortunately, the metadata and tagging services don't seem to specify a height and will grab the original. The resized versions I guess are only used in the UI (not checked). The tagging service is even explicit in not specifying a height so that it will grab the original.
https://github.com/Lidarr/Lidarr/blob/f50556d4d5ad84812fc1ee14af2d1f4d01bf9c07/src/NzbDrone.Core/Extras/Metadata/Consumers/Roksbox/RoksboxMetadata.cs#L171
https://github.com/Lidarr/Lidarr/blob/f50556d4d5ad84812fc1ee14af2d1f4d01bf9c07/src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs#L214
https://github.com/Lidarr/Lidarr/blob/f50556d4d5ad84812fc1ee14af2d1f4d01bf9c07/src/NzbDrone.Core/MediaFiles/AudioTagService.cs#L89

Specifying defaults for these services should at least prevent the large files being copied to every audio file in an album or as metadata in the folder for kodi, etc. This would probably need to be configurable though.

**Comment by Qstick** [comment]
Thought you guys wanted the BEST! I personally can't live without my 100mb album art!!!

On a serious note, We will take a look at optimizing this...

**Comment by Qstick** [comment]
Pushed some code to metadata that should sort this out, or make it better at least. Covers are limited at 1200x1200 now for Lidarr purpose

**Comment by zandadoum** [comment]
> Pushed some code to metadata that should sort this out, or make it better at least. Covers are limited at 1200x1200 now for Lidarr purpose

Hello,
any chance we can set this up in options?

my regular covers are like 150KB at most, but with the current (latest) lidarr version many covers go up to 800KB or even 1MB, which is a huge increase, when i just want a tiny cover that will show on my iPod

thank you
