### ISSUE TITLE
request bring back musicbrainz

### ISSUE THREAD

**Issue by Fish2** [lidarr/Lidarr#151]
Any chance you can bring back musicbrainz with the ability to use you own self host musicbrainz sever ?

Thanks

**Comment by Qstick** [comment]
We are using musicbrainz so bringing it back won't be necessary. You can already do this, but you also need to run your own lidarr metadata api. Then just change the metadata server path in settings.

**Comment by Fish2** [comment]
Ok saw a commit a long time back saying that you moved from musicbrainz to iTunes 
can you not build in Metadata api ? 
how dose Sonarr and Radarr deal with this ?

**Comment by Qstick** [comment]
Can we build it in? Yes
Are we going to? No

There are too many advantages for us to use a server side api interface between Lidarr and Musicbrainz (or other provider):

- Musicbrainz API is painfully slow and doesn’t fit our need, we bypass it.
- We can make quick changes for the entire install base when we have a provider schema change, instead of relying on each user to update Lidarr to get things working again.
- We can cache responses to minimize response time for the entire install base.

Sonarr and Radarr both use server side utilities to help with interfacing to their external providers and various other tasks.

If you want to discuss further or need help setting up a local instance feel free to get on discord.

**Comment by pdupreez** [comment]
I went to the MetaData settings, and clicked on the "info" link to see how to set this up.....and nothing?

On a follow up on the original question, does Lidarr use any type of acoustic fingerprinting, or does it purely depend on filename/tags?

**Comment by danielunderwood** [comment]
To set up your own metadata server, you'd have to run lidarr/LidarrAPI.Metadata and point the url in settings to it. However, that is not recommended as you'd have to run that application's dependencies as well and would experience worse performance.

We are not using any acoustic fingerprinting at this time.
