### ISSUE TITLE
cant add and save any indexer/Torznab

### ISSUE THREAD

**Issue by icf20** [Lidarr/Lidarr#2315]
`Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings.`

hello is the query is ok let me save the indexer FFS

[AB#1246](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1246)

**Comment by RobinDadswell** [comment]
Firstly please fill in the template fully so that we have all the required information. 

What indexer is it? Within the trace logs it should give you the exact query that it is running as part of the test, this should return some results. 

The reason we don't allow the indexer to add without returning results is as we cannot verify that it's actually functioning as an indexer without the results - it does a call to the indexer with the categories and this should return a page of results.

**Comment by ta264** [comment]
Generally public torrent trackers don't work with lidarr. You need a specialized music tracker. Visit discord for support.

**Comment by icf20** [comment]
@RobinDadswell > What indexer is it?

Every single one while they work with radarr and sonarr
