### ISSUE TITLE
[BUG]: On Release Import trigger not working for Discord Connection

### ISSUE THREAD

**Issue by valleyman89** [Lidarr/Lidarr#2443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a release has finished downloading, and Lidarr has imported it, _and_ you've set up a Connection for Discord, then a message is not being sent to Discord to confirm import of the release.

### Expected Behavior

When a release has been imported, 'On Release Import' trigger should activate and send a message to Discord to confirm the import

### Steps To Reproduce

1. Set up a Discord Connection in Lidarr
2. Grab a release
3. Lidarr will send a message to Discord to say a release has been Grabbed
4. Wait for Lidarr to import the release
5. There will be no message to confirm the release import in Discord, even though the trigger is enabled

### Environment

```markdown
- OS: Unraid OS 6.9.2
- Lidarr: 0.8.1.2135
- Docker Install: Yes
- Using Reverse Proxy: No
```

### What branch are you running?

Master

### Anything else?

trace logs excerpt of error:  [https://hastebin.com/vekisijoqi.yaml](https://hastebin.com/vekisijoqi.yaml)

Other triggers are working (e.g. On Grab)

[AB#1750](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1750)

**Comment by Drazzilb08** [comment]
Can confirm this issue still persist on the current nightly build

`1.0.0.2350`

Steps taken to reproduce same as above.

**Comment by ac3d912** [comment]
Discord webhook is returning `{"embeds": ["0"]}` on the webhook POST.  I captured this POST (redacted out unimportant things) and the thumbnail url is invalid (well, relative url, which Discord doesn't like).  Thanks to this [SO Answer](https://stackoverflow.com/questions/53935198/in-my-discord-webhook-i-am-getting-the-error-embeds-0) looks like a bad url will certainly trigger that response.

I'm running Lidarr nightly 1.0.0.2385; has the same issue.

```
{
  "embeds": [
    {
      "description": "Album Imported",
...
      "thumbnail": {
        "url": "/MediaCover/Albums/1641/cover.jpg?lastWrite=636134058260000000"
      },
...
]
}
```

Thumbnail URL Assignment https://github.com/Lidarr/Lidarr/blob/c2adf078345f81012ddb5d2f384e2ee45ff7f1af/src/NzbDrone.Core/Notifications/Discord/Discord.cs#L50

Since it looks like it's trying to use a relative URL to Lidarr... is there an external URL stored somewhere?  Put a check to ignore relative urls?

**Comment by ac3d912** [comment]
I did a bit more research on this, looks like the actual problem happens when broadcasting the import event. The API wants to modify the resource to use the local images (AlbumControllerWithSignalR.MapCoversToLocal; makes sense), but it is modifying the underlying `Images` collection (a List<MediaCovers>) which is used by the remaining event handlers.

https://github.com/Lidarr/Lidarr/blob/423e492569f5e9fdee638fe816f518cab1bef9d7/src/Lidarr.Api.V1/Albums/AlbumControllerWithSignalR.cs#L41-L53

The call stack looks like this...
```
>	Lidarr.Api.V1.dll!Lidarr.Api.V1.Albums.AlbumControllerWithSignalR.MapToResource(NzbDrone.Core.Music.Album album, bool includeArtist) Line 53	C#
 	Lidarr.Api.V1.dll!Lidarr.Api.V1.Albums.AlbumController.Handle(NzbDrone.Core.Music.Events.AlbumEditedEvent message) Line 173	C#
 	Lidarr.Core.dll!NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent<NzbDrone.Core.Music.Events.AlbumEditedEvent>(NzbDrone.Core.Music.Events.AlbumEditedEvent event) Line 96	C#
 	Lidarr.Core.dll!NzbDrone.Core.MediaFiles.TrackImport.ImportApprovedTracks.Import(System.Collections.Generic.List<NzbDrone.Core.MediaFiles.TrackImport.ImportDecision<NzbDrone.Core.Parser.Model.LocalTrack>> decisions, bool replaceExisting, NzbDrone.Core.Download.DownloadClientItem downloadClientItem, NzbDrone.Core.MediaFiles.TrackImport.ImportMode importMode) Line 127	C#
 	Lidarr.Core.dll!NzbDrone.Core.MediaFiles.DiskScanService.Scan(System.Collections.Generic.List<string> folders, NzbDrone.Core.MediaFiles.FilterFilesType filter, bool addNewArtists, System.Collections.Generic.List<int> artistIds) Line 163	C#
 	Lidarr.Core.dll!NzbDrone.Core.MediaFiles.DiskScanService.Execute(NzbDrone.Core.MediaFiles.Commands.RescanFoldersCommand message) Line 284	C#
 	Lidarr.Core.dll!NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand<NzbDrone.Core.MediaFiles.Commands.RescanFoldersCommand>(NzbDrone.Core.MediaFiles.Commands.RescanFoldersCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) Line 84	C#
```

Likely the best way to fix it is to copy the MediaCovers in the Images collection before mapping to local resources (in AlbumControllerWithSignalR.MapToResources or AlbumResourceMapper.ToResource). I can put together a PR, and submit it here in a couple of days.
