### ISSUE TITLE
One or more albums expected in this release were not imported or missing

### ISSUE THREAD

**Issue by martinkeat** [Lidarr/Lidarr#2862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After download completes in SABNZBD, item shows yellow marker in "Activity" and states: "One or more albums expected in this release were not imported or missing".

Not sure if this is (a) a bug, (b) an option I need to enable in order to simply have lidarr import anyway; or (c) a feature request for lidarr to important anyway.

In anycase, my SABNZBD history is backed up to the tune of 140 downloads waiting to import and it would take an absolute age to sit and manually click import again and again. 

### Expected Behavior

Should import files that have downloaded. 

### Steps To Reproduce

1. Download new album
2. Wait
3. See SABNZBD History is full.

### Environment

```markdown
- OS: Unraid Docker Container
- Lidarr: 1.0.2.2592 
- Docker Install: 
- Using Reverse Proxy: No
- Browser: All
```

### What branch are you running?

Master

### Trace Logs?

[Lidarr.txt](https://github.com/Lidarr/Lidarr/files/9084376/Lidarr.txt)

[AB#3355](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3355)

**Comment by martinkeat** [comment]
Any work around because it is doing my nut in?

**Comment by p6002** [comment]
Any fix for this bug? Just move album folder to artist folder. Dont compare, dont check any 80% of something. Just copy like in Radarr.

**Comment by MRobi1** [comment]
This has always been my #1 annoyance of using Lidarr. It's barely automated at all since I have to log in on almost a weekly basis and manually import 90% of everything it downloads. 

+1 for making it work more like Sonarr where an Album would be viewed as a "Season" and the individual Tracks viewed as "Episodes". Then if the download only contains 80% of the album Lidarr can start filling in the blanks with individual tracks. This should just be a no-brainer!
