### ISSUE TITLE
Support for creating backups via API

### ISSUE THREAD

**Issue by bmatheny** [Lidarr/Lidarr#2997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I am going through and automating backups for my servarr applications, and lidarr is the only one I have run into so far that doesn't support APIv3 backups.

The APIv3 backup command allows you to initiate a backup. The current APIv1 used by lidarr doesn't allow you to initiate a backup, only to list/delete/restore.

The proposed feature request would be to either extend the v1 backups endpoint to support initiating backups, or to bring in parts of the v3 command API.

### Describe the solution you'd like

Since lidarr has for some reason not adopted the v3 API, I'm assuming that the developers would prefer to see `/system/backup` modified. My recommendation would be to support a POST to `/system/backup`, with no arguments (this is equivalent to v3 API).

### Describe alternatives you've considered

Wholesale port the v3 command API but that seems messy.

### Anything else?

I would be happy to put up a PR for the proposed solution assuming nobody is working on this. A couple of questions.

1. My overall sketch for the solution would be to make two changes. First would be to support a POST against `/system/backup` in the v1 API, and the second would be to leverage the tasks infrastructure to create a task for a backup when the `/system/backup` endpoint receives a request. Thoughts?
2. Is there a reason that the v3 API hasn't been adopted, like it has for other servarr projects? Just curious.
3. Anything I should be aware of before I get started?

Thanks.

[AB#3802](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3802)

**Comment by Qstick** [comment]
Lidarr's v1 API is equivalent to Radarr and Sonarr v3. If you can trigger backup creation in UI then you can also do it via API.

**Comment by bmatheny** [comment]
I looked at the source code and there’s no code to handle initiating a backup via the API. @Qstick can you point at the relevant code or documentation?

**Comment by Qstick** [comment]
You can see here in the BackupService that a [BackupCommand ](https://github.com/Lidarr/Lidarr/blob/4985024dd6166972f42205d3408f28b3bdd78641/src/NzbDrone.Core/Backup/BackupCommand.cs#L5) is handled identical to Radarr and Sonarr

https://github.com/Lidarr/Lidarr/blob/4985024dd6166972f42205d3408f28b3bdd78641/src/NzbDrone.Core/Backup/BackupService.cs#L237

https://github.com/Sonarr/Sonarr/blob/d2a23f7bcdf71800f019644d7b6b5d712e311d7f/src/NzbDrone.Core/Backup/BackupService.cs#L241

This like all other commands is triggered through the [command endpoint](https://lidarr.audio/docs/api/#/Command/post_api_v1_command). Identical in functionality to Radarr and Sonarr, just using `v1` in the url instead of `v3`

Hitting backup in the UI, one can see a good example of how this works and teh call being made in Chrome's network tab. Everything the UI does is done via the API

![image](https://user-images.githubusercontent.com/376117/192075899-3c94cb62-879a-4e87-ae8a-e9da9608fa6d.png)

**Comment by bmatheny** [comment]
Got backup working against `/api/v1/command`. Thanks for the pointers @Qstick !
