### ISSUE TITLE
Edit album release from manual import

### ISSUE THREAD

**Issue by jw1986** [lidarr/Lidarr#347]
## Feature Request
Edit album release from manual import page on Queue > Activity

### Description of request and what problem are you looking to solve?
When you do a manual import on the Queue > Activity page, it would be great to have an option or drop down there to change the release of the album to match what was downloaded.  

For example Lidarr has the album set to the regular edition, but the download was the deluxe edition - currently you have to close the manual import screen, click on the album, click on edit, select the release, save, go back to Queue > Activity, then restart the manual import of the dowload and match the tracks.

Or better yet, have Lidarr make an educated guess on the release by checking the number of files in the download and finding an album that matches.

**Comment by distinguished-git** [comment]
What does Lidarr do if:
1. The target release selected by Lidarr for the monitored album is the standard (US) version; and
2. There are 0 tracks in Lidarr for this album; and
3. Musicbrainz Picard tags (including releaseID) my files as the deluxe (JP) version, with 4 bonus tracks; and
4. I do a manual import (quick, no interaction)?

What does Lidarr do? Does it change the wanted release to the deluxe (JP) version, which I am trying to import?

*If Lidarr changes the target release to deluxe (JP),* what does it do if I previously imported 1+ standard (US) tracks into my Lidarr library? Does it move them to the trash, since the previous import doesn't match the target release for this album? Maybe it can do so, but only if the new target contains more tracks?

**Comment by Qstick** [comment]
Yea I’ll take a peek at it.
