### ISSUE TITLE
Refresh album doesn't see missing file(s) you rename

### ISSUE THREAD

**Issue by leaderdog** [lidarr/Lidarr#366]
I'm assuming this is a bug.

Others have mentioned how if a song title is spelled incorrectly lidarr ignores it.  Fine, but if you rename the file to what Lidarr expects to see, there is no way (or at least I can't find it) to refresh that specific album to see anything new added to that folder.

steps:
1) imported several albums from one band just to test.
2) noticed many albums had 1 or 2 files missing.
3) did preview rename to reorganize the files to lidarr settings that I setup.
4) copied the songs that were not moved over into the new location and corrected the name of the file.
eg  file was  (not sure if names should be in here) 
*owerman 5000 - *uilders Of The Future - 04 - You're Gonna Love It, Like It Or Not.flac
Lidarr expected the song to be this "You're Gonna Love It, If You Like It or Not"
5) nothing happens in lidarr.
6) no option in the specific album name to correct song title or to have it refresh/rescan directory.
7) Manage tracks only allows you to manage the files lidarr actually has seen, so they don't show up in there.
8) back up and hit Refresh & scan.  Still doesn't see the missing song title.

I'm at a loss.  I would assume there should be a fairly simple way to correct errors that lidarr makes.

Any help is appreciated.

I forgot to mention I installed lidarr from the windows installer.
version: 0.2.0.371— Apr 21 2018
develop

Says it's the latest version but appears github has newer releases.

Here is the code from log when I hit the "Update All button in the Artist section:
`18-5-25 10:12:09.6|Info|RefreshArtistService|Updating Info for Powerman 5000
18-5-25 10:12:10.6|Info|DiskScanService|Scanning Powerman 5000
18-5-25 10:12:11.3|Info|DiskScanService|Completed scanning disk for Powerman 5000
18-5-25 10:12:11.3|Info|ExistingMetadataImporter|Found 0 existing metadata files
18-5-25 10:12:11.3|Info|ExistingLyricImporter|Found 0 existing lyric files
18-5-25 10:12:11.3|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
18-5-25 10:12:11.3|Info|ExistingExtraFileService|Found 0 extra files
18-5-25 10:12:11.8|Info|MediaCoverService|Downloading Fanart for [0a41f86c-ced1-44e0-95a2-5c8b2368ab1d][Powerman 5000] http://assets.fanart.tv/fanart/music/0a41f86c-ced1-44e0-95a2-5c8b2368ab1d/artistbackground/powerman-5000-4fd3160858627.jpg
18-5-25 10:12:15.3|Info|MediaCoverService|Downloading Logo for [0a41f86c-ced1-44e0-95a2-5c8b2368ab1d][Powerman 5000] http://assets.fanart.tv/fanart/music/0a41f86c-ced1-44e0-95a2-5c8b2368ab1d/hdmusiclogo/powerman-5000-5acdefbb60360.png
18-5-25 10:12:16.5|Info|MediaCoverService|Downloading Poster for [0a41f86c-ced1-44e0-95a2-5c8b2368ab1d][Powerman 5000] http://assets.fanart.tv/fanart/music/0a41f86c-ced1-44e0-95a2-5c8b2368ab1d/artistthumb/powerman-5000-50d646bd3a862.jpg`

**Comment by Qstick** [comment]
Did you fix the tags as well, we don't even use filename. All about the tags

**Comment by leaderdog** [comment]
tags?  Where would I go to mess with tags?  

and what exactly would the tag do to confirm that a file existed on the harddrive?

I think I'm confused about this.  Sonarr I'd just change a file name and refresh that particular tv show and it would realize the file existing on the harddrive.

**Comment by leaderdog** [comment]
update:
I can't view lidarr from my other pcs, only the pc it is installed only (localhost), so I tried messing with the bind ip, and that futz everything up, so I uninstalled it, deleted the lidarr folder in programdata and reinstalled.

I imported the folders that I originally had issues with and Lidarr isn't able to see them.

**Comment by Qstick** [comment]
You need to run once as admin so that Lidarr can register with the system.

Tags store all metadata for music, etc id3 tags for MP3 files.

**Comment by leaderdog** [comment]
Thanks Qstick for responding again.

I ran the lidarr.exe as administrator but it still only works on the media server, My other PCs show connection timed out.

Running it as administrator didn't give me the popup to allow it to be shared through the firewall.

I tried opening the port as well as the lidarr.exe program in windows firewall and I still cannot connect to it via my internal internet.

As for the tags, I'm still confused as to what the tag will do to make it so lidarr sees the actual .flac file.  It shows9/10 songs and I cannot get it to see the remaining file in the folder.

3 of the 6 albums are missing 1 or 2 songs.  They're physically there on the harddrive, just Lidarr won't read them and add them as part of the album.

**Comment by Qstick** [comment]
When you click manual import for that artist it should show remaining files and tell you why they didn’t import automatically

**Comment by Qstick** [comment]
Join our discord server for further support help

**Comment by aaronkenneally** [comment]
Lidarr is a great idea gone bad. Your program seems to only read meta data and ignores actual filenames. So as a compromise, Lidarr has the ability to rename files to clean them up similar to Sonarr and Radarr so why don't you allow a fallback that it looks for the META track number and then it can rename the track name it to whatever it wants? Lidarr has so much potential and this could solve everyones problem with it, instead the over reliance on Meta Titles matching perfectly forces users to have to resort to other meta editors to get them into the system which should be able to handle it with ease.

**Comment by Qstick** [comment]
@aaronkenneally 

1. We are still in infancy at barely a year old since we forked off of Sonarr, if you look at open issues you will see that we have plans to expand our parsing and parsing fallback to include file names, we wanted to get things to a working state before aiming for greatness.

2. We utilize metadata as the main source of data because file names for music are all over the the map. There is no standard, There are no rules, and everyone likes their music sorted and named differently. Therefore we have found that we are much more successful in matching metadata than we are in matching file names. Especially given file system limitations for file names, etc... 

3. If we just use Meta track number and assume a match we get a ton of bad renames due to the amount of different releases a single album could have. Track 1 for the US version could be completely different than track 1 of the European version. Without looking at the title as well we are bound to rename your files incorrectly, and then you will really be bashing us.

4. I'm very happy to see you take full advantage of the emoji system, looks like you liked your post sooooo much you wanted to give it a thumbs up. I support that level of confidence!! 👍 

While Lidarr does require some level of manual intervention at many points at this stage of development, the development decisions made thus far have been made with users data integrity in mind and with 30k unique users there is alot we could f-up!

Lastly, as always we welcome any contributions through time, code, or just testing and constructive feedback.
