### ISSUE TITLE
Custom format(s) arent being applied to names

### ISSUE THREAD

**Issue by klepp0906** [Lidarr/Lidarr#3670]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I'm attempting to use this 

> [{Custom Formats }{Quality Full}]

however it seems to be not taking the {Custom Formats } bit into account whatsoever.   It still leaves me with just [FLAC] as opposed to [CD FLAC] for example. 

### Expected Behavior

using [{Custom Formats }{Quality Full}] in your track naming should append the quality with whatever custom format(s) youve enabled 

> include in {Custom Formats} renaming format

with. 

### Steps To Reproduce

1 using lidarr nightly, create a custom format for CD for example, be sure to enable it to be used in naming.
2 under media management add {Custom Formats} somewhere in your track naming.
3 attempt to rename your track(s) and notice it seems to be entirely ignored

### Environment

```markdown
- OS: Windows 11 
- Lidarr: 1.2.1.3193
- Database: Sqlite 3.36.0
```

### What branch are you running?

Nightly

### Trace Logs?

https://0bin.net/paste/zJsHjueP#Azzr9FMkM+fsN9uycI8OVhrRN2PYKZlzcEhhYuLhQhW

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have followed the steps in the wiki link above and provided the required trace logs that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Logs don't exist?

**Comment by klepp0906** [comment]
yea i deleted em and closed the issue as it turned out to be a regex problem.  forward slashes and not backslashes, yay ;p
someone re-opened it,  unsure why.

only behavior im seeing now is the custom format naming isnt retroactive when doing a rename.  I can only assume this is due to the database not seeing it in the original filename during the original grab.

in this particular instance I was just trying to have it display CD or WEB which makes me wonder how the {medium format} is working retroactively and discerning between digital and cd if not original filename but thats off-topic.

**Comment by klepp0906** [comment]
oh no, having it retroactively applied would certainly be the ideal/preferential behavior.  open it is then.   I just wasnt sure if thats how it was expected/intended to function or not.

**Comment by klepp0906** [comment]
just to add to this, as ive still been working to get naming the way i want and running into all kinds of walls.  Seems its only sometimes applying the CF naming to new imports. 

sometimes its working, sometimes its not, and i cant ascertain what the differing variable is.

I just grabbed 2 CD releases, never been in my library before, folders were created without the CF name.  one album is being misidentified as digital media even though i grabbed a CD release via interactive search (which is one thing preventing me from just using {medium format} instead of {custom formats}).  even when trying to force it to the CD via album > edit > release, it just... doesnt work.  ignores me when i hit save and retains the current format. 

does anyone know how lidarr determines the medium format?  what it uses?

**Comment by bakerboy448** [comment]
Nightly has better logging to debug this https://github.com/Lidarr/Lidarr/commit/2cf2ebcbb28a59537533f36e4433349dbd76b473

**Comment by ehula** [comment]
Any update on this? Sure would be nice to have.

**Comment by MaddyTP** [comment]
I'm running into this same issue.  It seems the custom formats work fine when searching for media, but once downloaded it parses the file name instead of the original grab title.  Additionally, the renaming function looks at the file name instead of the original grab title.

**Comment by bakerboy448** [comment]
> I'm running into this same issue.  It seems the custom formats work fine when searching for media, but once downloaded it parses the file name instead of the original grab title.  Additionally, the renaming function looks at the file name instead of the original grab title.

This is by design and intentional

Release Parsing is always disconnected from On Disk Import Parsing

**Comment by tjaena** [comment]
Hey, I think I ran into this too on a recent nightly build (3.1.3.4977). Not sure if it's related but the symptoms look the same, so figured I'd share what I found in my logs in case it helps.

### My setup

- Track naming format:
  ```
  {Album Title} ({Release Year}){ (Album Disambiguation)}/{Track:00} - {Track Title} {[Custom Formats]}{[Quality Full]}{[MediaInfo AudioChannels]}{[MediaInfo AudioBitsPerSample]}{[MediaInfo AudioSampleRate]}{-Release Group}
  ```
- I made a Custom Format called "WEB Source" with a Release Title regex condition of `\b(WEB)\b`, and checked "Include Custom Format when Renaming".
- The release I grabbed was named something like `Guns_N_Roses-Use_Your_Illusion_I-REMASTERED-24BIT-WEB-FLAC-2022-GP-FLAC` (from usenet, came as a multi-part rar).

### What I saw

The "WEB Source" format shows up fine when I'm looking at search results, so the matching itself seems to work there. But once the album gets imported and renamed, it just doesn't show up in the filename at all, like it was never matched. Example filename I got:

```
/data/media/music/Guns N’ Roses/Use Your Illusion I (1991)/01 - Right Next Door to Hell [FLAC 24bit][2.0][24bit][96kHz]-02+50.flac
```

No "WEB" anywhere even though Quality Full and the MediaInfo tokens all showed up fine.

### What I noticed in the trace logs

I turned on trace logging and searched around, and found this line that repeats a lot during import:

```
2026-07-21 13:46:33.6|Trace|CustomFormatCalculationService|Using original file path for release title: 01-guns.n.roses-right.next.door.to.hell.flac
```

That looks like it's just using the plain track filename, not the original release name. And earlier in the same log there's this line, which does have the full path including the folder/rar name:

```
2026-07-21 13:46:33.4|Trace|IdentificationService|Mapped /data/usenet/complete/music/[02+50] Guns_N_Roses-Use_Your_Illusion_I-REMASTERED-24BIT-WEB-FLAC-2022-GP-FLAC.part01.rar/01-guns.n.roses-right.next.door.to.hell.flac to [89d57b63-dca8-462a-9544-ab30dc288b27]Right Next Door to Hell, dist: 0
```

That folder name has "WEB" right in it, so I'm guessing that's the piece that would have made my regex match, but it seems like it's not what's actually being used later on when the custom formats get calculated for naming. I saw this same pattern repeated for all 16 tracks in the album, so it doesn't seem like a one off thing for me at least.

I'm not really sure if this is the same root cause as the original report or something different, and I don't know the codebase well enough to say what the actual fix should look like. Just wanted to share the logs in case they're useful for figuring out what's going on. Happy to attach the full trace log if that would help.

### Trace Logs
https://logs.notifiarr.com/?df4d2b491340e3bc#9Ysvn9GJCh7RiCgeanrhq5Yqd1LAYBZ7SD24YunUFYM
