### ISSUE TITLE
Change Artist musicbrainz id

### ISSUE THREAD

**Issue by GugZi** [Lidarr/Lidarr#389]
the ability to change musicbrainz artist / album id

[AB#438](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/438)

**Comment by sasjafor** [comment]
But can you actually add an artist by musicbrainz ID? Because when I attempt a manual import for an artist that wasn't found by lidarr, I can paste the ID, but lidarr still can't find it.

Example: Lang Lang (43e1570a-1a0d-479f-9c95-fba971aec91a), which has Chinese Signs as the official name on musicbrainz.

**Comment by benklop** [comment]
I have a similar issue where my artist is not in the top 10 results, so isn't selectable when importing.

**Comment by danielunderwood** [comment]
@benklop you should be able to add manually by searching for `mbid:` followed by the musicbrainz ID of the artist. If it's a common issue, it may be worth opening up a feature request for loading more search results if needed.
