### ISSUE TITLE
Allow more manual usage of Lidarr

### ISSUE THREAD

**Issue by ismay** [lidarr/Lidarr#404]
## Feature Request

First off, my compliments on the project, best music downloader so far. However, in using it I encountered a couple things that, though I like the project, made it less than ideal to use.

### Description of request and what problem are you looking to solve?

I personally treat my music collection differently than my shows and movie collection. I care a great deal about the organization, quality and accuracy of the rips in my music library. So I’ll manually verify the logs and cue files, and copy them over, use beets for renaming, etc. I don’t really care that much about that with my movies and series, and I’ll trust radarr and sonarr to manage the libraries.

Also, unlike movies and series, which I rarely watch more than once, I (of course) relisten the same music a lot. So not just the bitrate matters, but the accuracy of the rip, type of rip, etc. For example, I prefer rips from cd and not lp (personal preference), which means that I’m not always looking for the highest bitrate.

To help with organizing this all, I’m using a lossy and lossless folder for my music, and new downloads go to an import folder.

### So what does this mean

I would like more manual control over what Lidarr does. I’m a lot more involved with my music collection as opposed to my movies and series, and I suspect I'm not the only one. I'm not really looking for a music manager. That's what I have plex for. I'm looking for a music downloader. I would like to be able to:

1. Import artists from multiple folders (I have lossy, lossless, and import folders, all can contain _the same_ artist, currently it allows only one location per artist)
2. Download to an intermediate location. To make sure my music library stays organised and doesn't contain trash I use an import folder. From there I use beets to import. It would be nice if lidarr would download only to a specific location, instead of the folder where the original album is located
3. Dump the entire contents of the download, without removing anything (telling it to keep cue and log files did not work)
4. Be notified of new releases by artists in my library (I could not find this in the docs), or new found downloads (which I can then choose to download or not)

Currently in my opinion it is a bit too tied to the sonarr/series architecture. I think music downloading is a bit more messy and personal, so it should allow for a lot more manual intervention in my opinion. For those who are not as precise with their music collection automation might be nice, but I'd like it to be a bit more opt-in.

This is all of course quite personal, so I'll leave it to the devs to decide what to do with this info. I hope that this is of help in determining the direction to take lidarr in.

**Comment by alagave** [comment]
I heartily agree with these points. ismay has summed it up nicely. As in all software, this may require an advanced mode so it does not overwhelm the new or casual user. But, multiple import folders would allow the advanced user to maintain their archive in bitrate or genre based folders. The trick is to tell Lidarr that these are not 'really' duplicates. After all, some of us have 128-bit collections for portable media players and 320-bit and/or FLAC collections for home players. 

I think the Radarr/Sonarr architecture for searching and downloading is a good model. However, the back end or post-processing really needs to be different for audio files. When we look to the future (and I hope we are) there will be a need to accommodate audio files other than albums. And remember, Lidarr still cannot handle "Various Artists" albums.

So, when that major issue is in development would be the right time to consider **Compilations** (whether user or record label produced), **Mixtapes** (which appear as a single track but we do know the included track names and artists), **Live Performances** (which have set lists and sometimes arbitrary breaks between songs), **Podcasts** (which are similar to Mixtapes in structure but have an entirely different tagging requirement) and specialized constructs such as Swarms (many versions of the same song) or Tributes (songs or concerts done by an alternative performer).

These are legitimate needs of nearly every serious collector and will require a much more complex database than that required by Radarr or Sonarr. A good effort here could reap major payoffs in the future. It could even develop into into a super-set of MP3 tags that may never be incorporated into that standard but still provide the database structure needed for this project.

Lidarr could use some of the new tags to identify what would otherwise be considered duplicates while allowing the user to maintain multiple import folders based on Bit-rate, genre, language, country of origin or whatever.

**Comment by Qstick** [comment]
Closing this for now, feel free to add individual feature requests for items you’d like to see.

**Comment by lbesnard** [comment]
@ismay Thanks for this post. This is exactly what I'm experiencing and my workflow is very similar. I just want lidarr to automatically download better bitrates/new releases of my existing library into a tmp folder which I then will import or not with beets.

You said you followed @Qstick 's suggestion as "just setup your client to move Lidarr tagged downloads to a certain folder and the Lidarr will pick them up after you sort and process them into your main library"
I'm banging my head around this. I cannot seem to find the option in Lidarr to download albums in a folder and leave them there. Any tips?

**Comment by lbesnard** [comment]
oh I think I found it. It is an option in the "download clients" setting section, and not in the "media management" one
