### ISSUE TITLE
Cannot Add Album lidarr:d65e8d87-8a65-4da7-a132-01825325ab23 from Musicbrainz

### ISSUE THREAD

**Issue by jeffreyswiggins** [Lidarr/Lidarr#4814]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Is misreporting the information from Musicbrainz as:

yaya1324

Should be:

[Broken Compass Bluegrass](https://musicbrainz.org/artist/31e3ccb8-fac0-4df2-900f-06c2c2d572a7)
https://musicbrainz.org/release-group/d65e8d87-8a65-4da7-a132-01825325ab23
Album:  Through The Trees

### Expected Behavior

To be able to add the album: Through The Trees

### Steps To Reproduce

Click ADD  NEW
Type lidarr:d65e8d87-8a65-4da7-a132-01825325ab23

Searching returns no valid results for this band either

### Environment

```markdown
- OS: Ubuntu
- Lidarr: 2.4.0.4205
- Docker Install:nightly-47ec453 by hotio
- Using Reverse Proxy:yes but same results direct port
- Browser: Any Browser (Tried Chrome, Firefox, DuckDuckGo, Edge, Chromium, Brave)
- Database: Sqlite 3.44.2
```

### What branch are you running?

Nightly

### Trace Logs?

[lidarr.trace.txt](https://github.com/Lidarr/Lidarr/files/15362779/lidarr.trace.txt)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by oblomovx** [comment]
New release-groups are not showing up in Lidarr. I am aware of the following things:

- release-groups under voting can be a problem. But this release-group is not under voting and can not be added: https://musicbrainz.org/release-group/72dd3d5e-e137-41f7-841c-5c66671a290f
- release-groups that are not official can be a problem. But this release-group is official and can not be added: https://musicbrainz.org/release-group/4e5eda55-cbf2-4c08-b69d-735067b3bf3d
- "You are adding releases, not releasegroups". No, I am trying to add release-groups, see above
- You can request a refresh in the discord server. I did a couple of times, no change

My conclusion is: there is something wrong with the https://api.lidarr.audio/ server. I suspect it is because of the update the music brainz api did: https://blog.metabrainz.org/2024/05/13/musicbrainz-schema-change-release-2024-05-13-with-upgrade-instructions/

Please have a look at this again.
