### ISSUE TITLE
Can't disable RSS, or Automatic and Interactive Search if indexer's site is down.

### ISSUE THREAD

**Issue by tro-co** [Lidarr/Lidarr#547]
If an indexer's site is down, Lidarr will not permit disabling the RSS and/or the Automatic and Interactive Search check boxes.  When saving the changes, it checks the indexers site to make sure the settings are correct, but the site is down.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Indexers'
3. Select an Indexer
4. Select to either enable or disable one of the searches or RSS options when the indexer is offline.

**Expected behavior**
It should allow us to disable those options without the 'test' being performed.

**System info**
Version:                   0.4.0.524
DB Migration:          20
AppData directory:  C:\ProgramData\Lidarr
Startup directory:    C:\ProgramData\Lidarr\bin
Mode:                      Tray

Thanks.

[AB#461](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/461)

**Comment by Qstick** [comment]
If you uncheck all three it should bypass testing

**Comment by unikitty37** [comment]
That's all very well if you want to disable all three. I need to disable RSS and automatic searching on an indexer that I forgot I didn't have VIP on, and am thus over the limit.

With the way it currently works, I have to disable everything, go away until the limit resets, then remember that I wanted to re-enable the indexer for interactive search only.

It would be much easier to use if it could work something like this:

- User clicks `Save`.
- Tests fail, red `!` displayed on `Save` button.
- User clicks button while `!` is displayed.
- Dialog appears: "Are you sure you wish to save changes when tests are failing?"
- User clicks `Yes`.
- Data is saved.
- User can go off and do other things instead of having to keep trying to save until the indexer finally allows it.

Not allowing users to save invalid API keys is one thing but, in this situation, Lidarr should let us turn off automatic API connections and set an indexer to manual-only without requiring it to reset limits first 🙂

**Comment by bakerboy448** [comment]
Is this still an issue on 0.8 builds?

**Comment by bakerboy448** [comment]
Closing; no recent reports, force saving save x2 should work as well
