### ISSUE TITLE
[Question] Discogs integration

### ISSUE THREAD

**Issue by ClemDoum** [Lidarr/Lidarr#664]
Can someone describe the work needed to integrate Discogs as a data source in Lidarr ?

I already integrated it into my Headphone fork in a quick and dirty way. It was barely usable because of the limit rate they impose. I guess some advanced "caching" strategy is needed.

My current music download pipeline is way too time consuming, if @jpdillingham manages to integrate his Soulseek client [here](https://github.com/lidarr/Lidarr/issues/444), I think I'm ready to make the effort to integrate Discogs.

[AB#328](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/328)

**Comment by ta264** [comment]
It would require a fairly major rewrite because we rely on MusicBrainz IDs in a lot of places.

**Comment by Qstick** [comment]
What do you see as the benefit in discogs support? What would be the selling point?

**Comment by ClemDoum** [comment]
@Qstick  I dig music daily and use Discogs as a reference to find new releases, buy records or download them.

I often dig by label, and most small and independent labels reference their releases on Discogs but not on MusicBrainz. More generally I feel that record diggers in my community contribute more to Discogs than anything else because they use it daily to buy or sell music. Same for records shops, they add releases that they have in their shops to Discogs because if they want to sell a record online it needs to be on Discogs.

As a result MusicBrainz feels empty as soon as you use it to find less known releases, whereas Discogs has all the releases I need.

It would be interesting to precisely compute the ratio of the releases that I search on Discogs that are not available on MusicBrainz, but quickly looking at my record collection I can see that MB has only 50% to 60% of the releases. That wouldn't be a problem if releases missing on MB weren't available to download, but in a lot of cases I actually manage to find them.

Using MusicBrainz as single source in Lidaar makes it hard to use for me as in 50% to 40% of the cases I still need to have manual workflow.

**Comment by jpdillingham** [comment]
For what it's worth, I evaluated both MusicBrainz and Discogs recently in support of some stuff for Soulseek.NET and found the Discogs API to be less programmatically friendly.

I wasn't aware that Discogs was more complete so I may revisit it.

**Comment by ClemDoum** [comment]
@jpdillingham I do agree on the fact that it's less programmatically friendly.

I replaced MB with Discogs on my Headphones fork, in the end it was working but it was too slow because I had to deal with their API call limit rates. Then I tried integrating Soulseek and gave up at this point partly because I saw you work on Soulseek.NET and thought that you might manage to connect Soulseek to Lidarr, and thought that maybe I could try a Discogs integration.

To me Discogs offers the same advantages as Soulseek in terms of releases availability but on the search side. A lot of people around me only use these 2 in their daily manual music workflow (with optionally RED as an additional download source).

**Comment by ClemDoum** [comment]
Ok so to avoid using their API (too much or at all) I just saw that there are monthly dumps [here](http://data.discogs.com/).

**Comment by Qstick** [comment]
Musicbrainz IS much more development friendly for sure. Seamless database replication on hosted copies of the server, robust and extensive database schema (now with genres), extensive relationship network both internal to the db and external to other sources (aucustId, cover art archive, last.fm, wiki, theaudiodb, fanart.tv, etc..). It’s hard to beat how easy they make things in terms of development and data organization. That being said the discogs db is much larger (cant comment as to the quality of entries though). We designed things to one day support multiple sources, but as @ta264 mentioned a lot of backend work is involved to make things seamless to the user.

**Comment by ta264** [comment]
I have been giving this a little bit of thought as to how we could approach this on the Lidarr side.  It would be helpful to confirm exactly what the aim is.  Which of these do you see as the main advantage of Discogs over MusicBrainz?

1. Discogs has artists that MusicBrainz does not
1. For artists listed on both, Discogs has albums that MusicBrainz does not
1. For Albums listed on both, Discogs has versions that MusicBrainz does not

Looking at the MusicBrainz database, approximately 500k of the 1.4m artists are linked to the corresponding discogs artist.

A full merge of the two datasources may be challenging but depending on the goal a partial merge may be more achievable.

**Comment by ClemDoum** [comment]
Hi @ta264 thanks a lot for giving it a thought ;)
To me the main advantage of Discogs over MusicBrainz is the point 1: Discogs has artists **and releases** that MusicBrainz does not

**Comment by ta264** [comment]
The "and releases" part - is that 2. or 3. or something different? Worth pinning down expectations exactly :)

**Comment by ClemDoum** [comment]
Sorry for releases I meant part `2`.

**Comment by LeoShivas** [comment]
I agre with the fact that I don't find artist AND releases with MB.
To my part, I use Plex Media Server to listen music which in connected to Last.fm.
I don't know if last.fm is better or not than Discogs, but, sure, it's better than MusicBrainz !

**Comment by kitsuneDEV** [comment]
Discogs has a lot more artists in their database then musicbrainz does.
I'd be very thrilled if Discogs could also be a source in Lidarr.

**Comment by salazr** [comment]
Just one more comment here, the reality is that likely outside mainstream artists, musicbrainz data is just ridiculously poor when it comes to releases. 

Another example: André Bratten EPs are entirely absent on music brainz. 

https://musicbrainz.org/artist/cbc8af2f-6809-4b9c-ae28-4d27e91d3497
https://www.discogs.com/artist/3283097-Andre-Bratten

What I have had to do is to start adding releases to musicbrainz, but it really defeats the purpose of automating the downloads with lidarr.

**Comment by Qstick** [comment]
True, but misicbrainz will never grow as a dataset without some help from us users. Now that you have added them the next guy will not have to 😁. Musicbrainz is completely open, open data, open source, and committed to bringing this information to the hands of everyone by offering developers and users easy ways to use said data. Things that we believe in whole-heatedly and want to help support and help grow.

**Comment by screwfaze** [comment]
Hi guys,

Discogs integration would be so awesome musicbrainz is lacking a lot of releases for me and makes using lidarr not so automatic when I have to keep doing everything manually all the time.

Thanks

**Comment by Protektor-Desura** [comment]
I would recommend that you get a Musicbrainz account and use Picard to scan your files and upload the info and audio fingerprints to Musicbrainz. The reason is Discogs is decent but it doesn't have anything to really tell you which version of an album it is that you own. Musicbrainz will do a fingerprint of all the tracks to help you figure out exactly which album you have, including the difference between UK & Japan & US, etc.

**Comment by brendan-pike** [comment]
A huge +1 for discog support from me. I use Picard heavily however I follow discogs Genre and Style guides as I believe they are the best on the net.

**Comment by kokogakayui** [comment]
Discogs integration would be awesome indeed :)

**Comment by IwishIcanFLighT** [comment]
Agreeing with the overall praise for a Discogs integration as their endless DB would be a major plus to Lidarr. :+1:

**Comment by marcw** [comment]
Huge +1 for discogs

**Comment by Phill23** [comment]
Huge +1 or last.fm like Plex uses for metadata.

**Comment by Chris230291** [comment]
Discogs is THE online database. Forget lastfm, itunes, amazon, musicbrainz etc.
Like others have pointed out, its the only place where the small self produced artists list their stuff.
Even more popular artists have massive chunks of their library missing on Musicbrainz.
Not to mention all of the incomplete and incorrect data on MB. I am sure we are all guilty of doing the least amount of work needed, not even checking if its correct, just to get a green icon in Lidarr.

You want to sell something in an online auction, you use ebay.
You want to look up music, you use Discogs.

That discogs data dump sounds like what we need long term. Maybe just use MB to fill in any gaps since the last discogs dump?

**Comment by JiSiN3000** [comment]
Discogs would be really really nice.
There are so many Albums missing on other online databases compared to Discogs.
Especially for foreign music. just a few moments ago i added on Lidarr another foreign musician and i got the following result:

Album(2 Releases)
Broadcast(0 Releases)
EP(0 Releases)
Other(0 Releases)
Single(0 Releases)

It's a pretty famous singer from the '60s to '80s.
Granted only in a few countries which all of them are non-english speaking countries.
but still, on Discogs the Result is 77 instead of 2.

I would be really happy if Lidarr would use Discogs in the future. :)

**Comment by TheTomCanuck** [comment]
Discogs support would be amazing. It's the only thing holding me back from using Lidarr to it's fullest. I own about 2200 CDs and I'd say at least a solid 75% of what I rip exists on Discogs but not MusicBrainz. I get that adding it to musicbrainz is a thing, but it's just so overwhelming when it's such a high percentage of my discs.

**Comment by screwfaze** [comment]
Given the number of people who would like discogs support I believe this should be something the devs consider adding to make lidarr even better for everyone. Musicbrainz just isn't good enough to be the only source.

**Comment by suikerchiller** [comment]
Adding Discogs metadata would be a major improvement and should definitely see a lot of support from Oink / What / etc users ;-) Just out of curiosity: when do you expect to make a decision @ta264 ?

**Comment by ta264** [comment]
Ive already made a decision - it's just not feasible given the discogs API.

**Comment by suikerchiller** [comment]
Too bad, but understandable. Hope it will be feasible one day!

**Comment by etetlow** [comment]
Considering that you can get a download of both MB and discogs databases, wouldn't it be feasible to write a script to find the difference between the 2 databases and then add it to MB? Not easy by any means, I know, but the fact remains that MB's api is far superior to discogs. Therefore adding the data missing from MB would be the best solution as it would mean no changes to Lidarr whatsoever.

Just an idea!

**Comment by linareyne** [comment]
I have issues downloading at ~75% of the things I want on Lidarr, because I'm going after new releases of experimental/contemporary classical/jazz by relatively small, independent labels. Musicbrainz absolutely sucks as a data source for these genres and independent labels - few labels seem to add data to Musicbrainz, and what is present is rarely up to date or tagged correctly.

Just checked over a dozen artists and albums that Lidarr/MB is giving me trouble about, and Discogs has all the data there. Lidarr is such a pain in the ass for me, but I really want an automation solution for music and I really think that Discogs integration would solve the majority of my issues.

**Comment by linareyne** [comment]
To me, Lidarr is basically worthless without a Discogs integration. Experimental music and independent releases/labels are so absent from Musicbrainz that Lidarr doesn't work for >90% of the stuff I'm trying to use it for.

I've been adding some data to MB, but it would literally be a full-time + overtime job to add my entire library. Instead of Lidarr being a useful automation tool, I'm currently spending more time on this, even without adding stuff to MB, than I was manually downloading, moving, and retagging files.

Meanwhile, Discogs exists and contains data on literally **_every single album_** out of ~50 albums/artists missing from MB that I've searched for over the past couple days. There has to be something we can do, @ta264. I'd be happy to help with whatever implementation could get us there, tho I can't guarantee a ton of time to it.

**Comment by Protektor-Desura** [comment]
There is a GreaseMoney script to auto import from Discog to Musicbrainz for you. It isn't 100% automated in that it won't do the whole database at once but you can easily pull in specific albums
https://wiki.musicbrainz.org/Guides/Userscripts

**Comment by etetlow** [comment]
That would help a lot. I can write a script to find the difference between the two. You'll have to give me a couple of weeks probably to fit it in. Watch this space!

**Comment by linareyne** [comment]
Yeah that at least makes things a little easier. Maybe we could at least have a discogs search/import to MB feature using such a script implemented within Lidarr? Seems like it'd be worth it to make Lidarr more useful out of the box.

**Comment by etetlow** [comment]
Not meaning to let the cat out the bag too early cause its a way off being done, but I'm working on an application to work alongside Sonarr, Radarr and Lidarr to automate metadata collection, conversion, file naming and movement of files from download.

Whilst doing this I've found that because of the changes in the music industry over the last couple of decades that there are a lot of artists out there that aren't signed to a label and their albums aren't released in the traditional way leaving both Discogs and MB none the wiser. I feel as though if these 2 services don't open their eyes and change with the times that they'll soon be a dying breed. Especially MB. I'm pretty sure that for the time being that I can get together a script that will download both databases, find the difference between the two and upload the difference to MB once a month or whatever time scale that they issue a new database. 

But looking at the future there is one place that holds all of the information needed to cover these new artists and its my main goal to find a way of being able to use this information whether it's via api or scraping. And that place is Soundcloud. Pretty notorious for making itself inaccessible but there's always a way around these things.

**Comment by linareyne** [comment]
MB just needs to step up their game... improve the interface; add more community features and whatnot to attract lay users (think IMDB);  pursue mutually beneficial, automated integrations with services like Discogs, Bandcamp, and Spotify; etc.

As always, it just comes down to "wouldn't it be great if we had a political-economic environment that actually valued repositories of information and cultural archives enough to ensure their success?"

**Comment by Chris230291** [comment]
As far as I know MB doesn't make it possible to add entries programmatically without some human input. I would have thought someone else would have already made a Discogs > MB scraper if that was the case. I hope I'm wrong.

If it does work, it would be nice if there was some way of tagging the entries "Discogs" and then having a way in Lidarr to prioritise entries with those tags. The biggest issue with MB, aside from it missing almost everything that's isn't popular, is that anyone can put in whatever info, correct or not.

**Comment by suikerchiller** [comment]
> But looking at the future there is one place that holds all of the information needed to cover these new artists and its my main goal to find a way of being able to use this information whether it's via api or scraping. And that place is Soundcloud. Pretty notorious for making itself inaccessible but there's always a way around these things.

Don't forget Bandcamp ;-)

**Comment by Chris230291** [comment]
And Beatport and Deezer... If they were all implemented in a *other superior database* > MB scraper, and my tagging idea could be implemented, perhaps users could have a priority order in Lidarr?

The Beets project (basically Lidarr without the downloading part and UI) have plugins for Discogs, Beatport, Deezer etc but prefers MB and that cant be changed. Might be worth looking at. https://beets.io/

**Comment by suikerchiller** [comment]
> https://wiki.musicbrainz.org/Guides/Userscripts
> https://github.com/murdos/musicbrainz-userscripts#discogs_importer

I've been using the discogs script via Chrome / tampermonkey and so far it has been working very well (it saves me ± 5 - 10 min per release). The script doesn't seem to fetch artwork though, anyone find an automated solution for that as well?

**Comment by Californian** [comment]
I believe this would also be useful because it doesn't seem that pending musicbrainz data is pulled into lidarr, which severely hampers my use case of listening to new music that comes out every day (or even week).

For example:
https://musicbrainz.org/release/f354913b-ba4e-4886-94c8-35108fe43092
and
https://musicbrainz.org/release/487dc821-64c5-4e99-8caf-744c75c15756

are both already on musicbrainz, but don't show up in lidarr (and it's been over a day for the first one).

If this is a separate issue and the intent was to allow pending releases (or there's a workaround), let me know and I'll create a new one.

**Comment by etetlow** [comment]
@Californian I did look into trying to find a resolution by writing a script to find the difference in databases but both databases are so haphazard that I deemed the effort too time consuming. I'm now looking into finding a resolution using the Sound Hound api but I don't know how up to date their records are. Any ideas or opinions are most welcome.

**Comment by pduchnovsky** [comment]
Musicbrainz does not have really best database, especially for foreign languages.
I saw "Alternative Metadata Source" in Lidarr advanced settings however link pointing for more info is leading to wiki where there is no information about this setting at all.
I was hoping to be able to define discogs as alternative metadata source.

**Comment by Protektor-Desura** [comment]
Optimally the best would be to scrape Discog database and import everything  from their database in to MusicBrainz then scrape Bandcamp, Deezer,  Beatport, SoundCloud, Microsoft Music, etc and merge all of that in to MusicBrainz. The biggest problem I see is that the add album interface for MusicBrainz is terrible. You could automating the scripting and merge it all in to your own MusicBrainz database all automated but if you can't merge your database changes easily to the official/original MusicBrainz database then it does no good.

**Comment by brendan-pike** [comment]
Just FYI there is a nice tagger https://github.com/Marekkon5/onetagger/ that includes support for discogs for reference.

**Comment by raudraido** [comment]
+1 for Discogs integration!

**Comment by Kirstens-Curiousities** [comment]
Reading this thread with interest as I spend a significant amount of time adding missing music to MusicBrainz so I have a greater view of my collection. I don't even use the downloading features, I just love the the way Lidarr presents my collection. Discogs integration would save me so much time - as would Spotify/Bandcamp integration. As far as I can see Lidarr makes a local database of data anyway?

**Comment by DjRicko** [comment]
MusicBrainz is pretty much useless for scandinavian artists without correcting and adding every single album to MB manually each time something releases.
https://musicbrainz.org/artist/f1272428-d9a5-4c96-acd4-6e9f59974fc0
This is one of Denmark's biggest artists and nothing has been added since 2013 and even 90% of the old stuff is missing.
Discogs is pretty much complete. But using the userscript to manually clone the data is a chore and would require an army of people to keep every artist updated.

**Comment by pavelvodrazka** [comment]
Hi @ta264, would it be possible to build the integration on top of this [C# Discogs client](https://www.nuget.org/packages/ParkSquare.Discogs/)? It supports authentication and structured search criterias like this:

```cs
var searchResult = await _client.SearchAllAsync(new SearchCriteria
{
    Artist = "2Pac",
    ReleaseTitle = "All Eyez On Me"
});
```
The documentation also contains an example how to handle request rate limits using [Polly](https://www.nuget.org/packages/Polly) library.

Although I'm not a C# guy it looks promising to me and it's distributed under the MIT license. I'm curious what do you think. Does it worth a try?

Integration with Discogs would be a huge step forward for Lidarr, so I'm still hoping...

**Comment by ggibby** [comment]
I've been tagging from Discogs via MediaMonkey for years, and the lack of support for it is another reason I wonder why anyone uses Lidarr.

**Comment by snds** [comment]
I have encountered numerous releases for artists I follow that are missing release variants in MusicBrainz, while Discogs has the release in question. This means my collection, purchased from the artist or their label, can be frustratingly incomplete.

The example I have in question is here: https://www.discogs.com/release/3847440-Hybrid-Fall-Out-Of-Love

Lidarr only shows 3 releases; the largest tracklisting is no more than 6 tracks. The release in Discogs is the one I have, but MusicBrainz doesn't have it.  would love there to be a way to either a) utilize Discogs as an alternate search and match mechanism or b) allow me some mechanism to submit a release to MusicBrainz with a way to add a release manually and enter the Discogs data manually or via a link that is scraped.

![hybrid-discogs](https://github.com/Lidarr/Lidarr/assets/570874/b15d3ae3-4d1d-48fc-9964-335a0c460061)

**Comment by etetlow** [comment]
> There is a GreaseMoney script to auto import from Discog to Musicbrainz for you. It isn't 100% automated in that it won't do the whole database at once but you can easily pull in specific albums https://wiki.musicbrainz.org/Guides/Userscripts https://github.com/murdos/musicbrainz-userscripts#discogs_importer

**Comment by nelsongraca** [comment]
> I've been tagging from Discogs via MediaMonkey for years, and the lack of support for it is another reason I wonder why anyone uses Lidarr.

Started using Lidarr to manage my collection and I'm having the same issue a lot of missing stuff from musicbrainz.

**Comment by snds** [comment]
> > There is a GreaseMoney script to auto import from Discog to Musicbrainz for you. It isn't 100% automated in that it won't do the whole database at once but you can easily pull in specific albums https://wiki.musicbrainz.org/Guides/Userscripts https://github.com/murdos/musicbrainz-userscripts#discogs_importer

I appreciate this, but the whole intent of my homelab and using apps like Lidarr is to be automated. If I were to manually do this for every album Lidarr tried to import and replace or match the wrong album to, it would be a full-time job.

**Comment by pentago** [comment]
Compared to Discogs, MusicBrainz suck in data for the music I follow. I would prefer an option to select custom metadata service..

**Comment by Qstick** [comment]
Not planned to add as an alternative data source right now, however feel free to continue discussion here
