### ISSUE TITLE
Root Folder Not Mapping

### ISSUE THREAD

**Issue by mccorkled** [lidarr/Lidarr#88]
I have everything setup properly (I know because I have setup Radarr and Sonarr) and when I try to add any artist I cannot. For this example I used Neil Young. 

Add Artist
Searched Neil Young
Clicked Neil Young
Root Folder Dropdown menu
Add New Path
Selected /music
Click 'ok'
Nothing at all happens. 

If I type in /music and click ok, the same thing happens... nothing.

![1](https://user-images.githubusercontent.com/13697804/31061617-26b6f8ee-a6f1-11e7-8041-554898cb5a2a.jpg)

Seems as though the user permissions are not working properly. I setup the PUID and GUID within Docker properly and Lidarr should have the user permissions it needs.

**Comment by danielunderwood** [comment]
This sounds a lot like a permissions issue. Docker accepting a UID/GID is dependent on the image being used and isn't really standardized. Are you seeing any errors in the logs? What does your Dockerfile look like?

Regardless of the issue, we should probably have some sort of feedback in the UI for an error.

**Comment by mccorkled** [comment]
https://pastebin.com/30aRXRdq

The entire top of the log is Lidarr looking for information from books that I have being snatched using a program called LazyLibrarian. Strange.

![1](https://user-images.githubusercontent.com/13697804/31096335-baa77ea0-a789-11e7-89fe-b7acc1c38e78.png)

**Comment by danielunderwood** [comment]
Looks to be a permission issue from `[v10.0.0.6791] System.UnauthorizedAccessException: Root folder path '/music/' is not writable by user 'nobody'`. I don't think it should be a lidarr issue since we should have the same file access backend as sonarr and radarr.

You may want to run `id` in the terminal to see if the group and user IDs that you're giving are actually being used. I know there's an image out there from @Starbix, but I think that one uses environment variables `UID` and `GID` instead of `PUID` and `GUID`.

**Comment by mccorkled** [comment]
Changing those variables did the trick. 

Thanks.

**Comment by Starbix** [comment]
I added a README to my dockerimages repo mentioning the UID/GID

**Comment by mccorkled** [comment]
Must have missed it. Sorry guys.

**Comment by Starbix** [comment]
Haha no, I added it after your issue 😄
